### ISSUE TITLE
mathtype 0.1.0 fails on equations that worked with version 0.0.7.5

### ISSUE THREAD

**Issue by mkraetke** [jure/mathtype#21]
In contrast to the previous version, mathtype mathtype 0.1.0 does not work with certain equations:
```
Mtef2Xml: (NoMethodError) undefined method `/' for nil:NilClass
```
Please find a [zipped example](https://github.com/jure/mathtype/files/9724488/oleObject1.zip) here.
